apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
      - name: interaction-service
        image: bonheur255/interaction-service:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: interaction-service
spec:
  selector:
    app: interaction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
